language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  target-branch: master
  keep-history: true
  on:
    branch: development
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"

